/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.view;

import erp.dao.ClientesDAO;
import erp.jdbc.ConnectionFactory;
import erp.metodos.SoNumeros;
import erp.objects.Clientes;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Renato
 */
public class ClienteUpdJD extends javax.swing.JDialog {
     Connection con = null;
     
     public ClienteUpdJD(Connection conexao) {
         this.con = conexao;
     }
    /**
     * Creates new form ClienteUpdJD
     */
    public ClienteUpdJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.con = ConnectionFactory.getConnection();
        initComponents();
        txtId.setDocument(new SoNumeros());
        txtCadTelefone.setDocument(new SoNumeros());
        cbUf.setSelectedItem(null);
        bloquearcampos();
    }
    
public void consulta() throws SQLException{
        
        int id = Integer.parseInt(txtId.getText());
        Clientes list = new Clientes(id);
        boolean existeid = existeID(list);
        if (existeid){
            String sql = "select * from clientes where id=?";
        try {
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs = null;
            pst.setInt(1, Integer.parseInt(txtId.getText()));
            rs= pst.executeQuery();
            
            if(rs.next()){
                txtCadNome.setText(rs.getString(2)); 
                txtCadRg.setText(rs.getString(3));
                txtCadCpf.setText(rs.getString(4));
                txtCadEndereco.setText(rs.getString(5));
                txtCadCep.setText(rs.getString(6));
                txtCadCidade.setText(rs.getString(7));
                cbUf.setSelectedItem(rs.getString(8));
                txtCadTelefone.setText(rs.getString(9));
                txtCadBairro.setText(rs.getString(10));
            }
            
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
        }else{
            JOptionPane.showMessageDialog(null, "ID não encontrado no Sistema");
        }
        
    }
 public boolean existeID(Clientes idClientes) throws SQLException {
       // Esse metodo vai consultar o banco e trazer dados ;
       String sql = "select * from clientes where id = ?";
       
       PreparedStatement st = con.prepareStatement(sql);
       ResultSet rs = null;
       st.setInt(1, Integer.parseInt(txtId.getText()));
       
       rs = st.executeQuery();
       
       //esses dados podem ser recebidos por esse metodo abaixo;
       // essa variavel result é o resultado da pesquisa no banco;
      ResultSet result = st.getResultSet();
      
       
        return result.next();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCadNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCadCpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCadRg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCadTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCadEndereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCadCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCadCep = new javax.swing.JFormattedTextField();
        txtCadBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbUf = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnDados = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar dados do cliente");
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(187, 187, 250));
        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Atualizar Dados");
        jButton1.setToolTipText("Adicionar");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 140));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 140));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(45, 139, 206));
        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 24));

        txtCadNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadNomeKeyPressed(evt);
            }
        });
        jPanel3.add(txtCadNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, 35));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novas/user (96).png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 120));

        try {
            txtCadCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadCpfActionPerformed(evt);
            }
        });
        txtCadCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadCpfKeyPressed(evt);
            }
        });
        jPanel3.add(txtCadCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 250, 35));

        jLabel2.setBackground(new java.awt.Color(45, 139, 206));
        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RG:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 24));

        txtCadRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadRgActionPerformed(evt);
            }
        });
        txtCadRg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadRgKeyPressed(evt);
            }
        });
        jPanel3.add(txtCadRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 250, 35));

        jLabel9.setBackground(new java.awt.Color(45, 139, 206));
        jLabel9.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Telefone:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 24));

        txtCadTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadTelefoneActionPerformed(evt);
            }
        });
        txtCadTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadTelefoneKeyPressed(evt);
            }
        });
        jPanel3.add(txtCadTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 250, 35));

        jLabel3.setBackground(new java.awt.Color(45, 139, 206));
        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CPF:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, 24));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 154));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 154));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCadEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadEnderecoActionPerformed(evt);
            }
        });
        txtCadEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadEnderecoKeyPressed(evt);
            }
        });
        jPanel2.add(txtCadEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 250, 35));

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Bairro:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 24));

        txtCadCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadCidadeKeyPressed(evt);
            }
        });
        jPanel2.add(txtCadCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 250, 35));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CEP:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 24));

        try {
            txtCadCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadCepKeyPressed(evt);
            }
        });
        jPanel2.add(txtCadCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 250, 35));

        txtCadBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadBairroActionPerformed(evt);
            }
        });
        txtCadBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadBairroKeyPressed(evt);
            }
        });
        jPanel2.add(txtCadBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, 35));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Endereço:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 24));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cidade:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 24));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("UF:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 27, -1));

        cbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUfActionPerformed(evt);
            }
        });
        cbUf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbUfKeyPressed(evt);
            }
        });
        jPanel2.add(cbUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, 35));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novas/home__96_-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jButton2.setBackground(new java.awt.Color(187, 187, 250));
        jButton2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Voltar ao Menu");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Atualizar Dados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Digite o ID do cliente para alterar seus dados :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 5, 317, 30));

        btnDados.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnDados.setText("Ver Dados");
        btnDados.setBorderPainted(false);
        btnDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDados.setFocusPainted(false);
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        jPanel4.add(btnDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 1, 119, 40));
        jPanel4.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 5, 104, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1493288_help_about_question_icon.png"))); // NOI18N
        jLabel14.setToolTipText("Se não sabe o ID , vá até a opção de pesquisar clientes no menu e procure o cliente desejado lá .");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setSize(new java.awt.Dimension(816, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    alterarClientes();
    limparcampos();
    bloquearcampos();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void txtCadNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadNomeKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadNomeKeyPressed

    private void txtCadCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadCpfActionPerformed

    private void txtCadCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadCpfKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadCpfKeyPressed

    private void txtCadRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadRgActionPerformed

    private void txtCadRgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadRgKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadRgKeyPressed

    private void txtCadTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadTelefoneActionPerformed

    private void txtCadTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadTelefoneKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadTelefoneKeyPressed

    private void txtCadEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadEnderecoActionPerformed

    private void txtCadEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadEnderecoKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadEnderecoKeyPressed

    private void txtCadCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadCidadeKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadCidadeKeyPressed

    private void txtCadCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadCepKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadCepKeyPressed

    private void txtCadBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadBairroActionPerformed

    private void txtCadBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadBairroKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_txtCadBairroKeyPressed

    private void cbUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUfActionPerformed

    private void cbUfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbUfKeyPressed
        // TODO add your handling code here:
        enter(evt);
    }//GEN-LAST:event_cbUfKeyPressed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(new Color(204,0,0));
        jButton2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(new Color(187,187,250));
        jButton2.setForeground(new Color(204,0,0));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
       try {
            if(txtId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Informe o ID");

            }else {
                try {  // abaixo foi feito uma validação para saber se existia o id informado.

           consulta();
           int id = Integer.parseInt(txtId.getText());
        Clientes list = new Clientes(id);
        boolean existeid = existeID(list);
        if (existeid) { // se o id informado existir , todos os campos ficam editaveis.
         
            JOptionPane.showMessageDialog(null, "Altere os campos que deseja, e em seguida clique em atualizar");
            ativarcampos();
        }else { // se não existir , os campos continuam sem interação.
            limparcampos();
            bloquearcampos();
        }
       } catch (SQLException ex) {
           Logger.getLogger(ClienteUpdJD.class.getName()).log(Level.SEVERE, null, ex);
       }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDadosActionPerformed

    
    public void enter(java.awt.event.KeyEvent evt){
    if (evt.getKeyCode() == evt.VK_ENTER){
            try {
                consulta();
            } catch (Exception ex) {
                Logger.getLogger(ClienteUpdJD.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteUpdJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteUpdJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteUpdJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteUpdJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClienteUpdJD dialog = new ClienteUpdJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDados;
    private javax.swing.JComboBox<String> cbUf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCadBairro;
    private javax.swing.JFormattedTextField txtCadCep;
    private javax.swing.JTextField txtCadCidade;
    private javax.swing.JFormattedTextField txtCadCpf;
    private javax.swing.JTextField txtCadEndereco;
    private javax.swing.JTextField txtCadNome;
    private javax.swing.JTextField txtCadRg;
    private javax.swing.JTextField txtCadTelefone;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

        private void alterarClientes(){
    int id;
    String nome, rg ,cpf , endereco , cidade , cep, uf , telefone,bairro;
    
    id = Integer.parseInt(txtId.getText());
    nome = txtCadNome.getText();
    rg = txtCadRg.getText();
    cpf = txtCadCpf.getText();
    endereco = txtCadEndereco.getText();
    cidade = txtCadCidade.getText();
    cep = txtCadCep.getText();
    uf = cbUf.getSelectedItem().toString();
    telefone = txtCadTelefone.getText();
    bairro = txtCadBairro.getText();
    
    Clientes obj = new Clientes();
    obj.setId(id);
    obj.setNome(nome);
    obj.setRg(rg);
    obj.setCpf(cpf);
    obj.setEndereco(endereco);
    obj.setCidade(cidade);
    obj.setCep(cep);
    obj.setUf(uf);
    obj.setTelefone(telefone);
    obj.setBairro(bairro);
    if ((txtId.getText().isEmpty()||txtCadNome.getText().isEmpty() || txtCadCpf.getText().isEmpty() || 
                        txtCadEndereco.getText().isEmpty() || txtCadRg.getText().isEmpty() || 
                        txtCadCep.getText().isEmpty() || txtCadCidade.getText().isEmpty()  ||
                         txtCadTelefone.getText().isEmpty() || cbUf.getSelectedItem().toString().isEmpty() ||
                        txtCadBairro.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos."); 
        
    } else {
        ClientesDAO objDao = new ClientesDAO();
        objDao.updateClientes(obj);
    }
    
    
 
    
    
    
    
}
    
    
    
public void limparcampos() {
      txtCadNome.setText(null);
        txtCadBairro.setText(null);
         txtCadRg.setText(null);
         txtCadCep.setText(null);
         txtCadTelefone.setText(null);
         txtCadEndereco.setText(null);
         txtCadCpf.setText(null);
         cbUf.setSelectedItem(null);
         txtCadCidade.setText(null);

}
   
public void bloquearcampos(){
    txtCadBairro.setEnabled(false);
        txtCadCep.setEnabled(false);
        txtCadCidade.setEnabled(false);
        txtCadCpf.setEnabled(false);
        txtCadEndereco.setEnabled(false);
        txtCadNome.setEnabled(false);
        txtCadRg.setEnabled(false);
        txtCadTelefone.setEnabled(false);
        cbUf.setEnabled(false);
        jButton1.setEnabled(false);
}

public void ativarcampos(){
    txtCadBairro.setEnabled(true);
        txtCadCep.setEnabled(true);
        txtCadCidade.setEnabled(true);
        txtCadCpf.setEnabled(true);
        txtCadEndereco.setEnabled(true);
        txtCadNome.setEnabled(true);
        txtCadRg.setEnabled(true);
        txtCadTelefone.setEnabled(true);
        cbUf.setEnabled(true);
        jButton1.setEnabled(true);
}











}
