/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.view;

import erp.controllernovo.ControllerVenda;
import erp.dao.ClientesDAO;
import erp.jdbc.ConnectionFactory;
import erp.objects.Clientes;
import erp.objects.ModeloTabela;
import erp.objects.Produtos;
import erp.objects.Venda;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Renato
 */
public class VendaViewJD extends javax.swing.JDialog {
    ConnectionFactory conn = new ConnectionFactory();
    Venda modelovenda = new Venda();
    int flag = 1,codVenda;
    float preco_produto,total = 0;
    private ProdutosConsultaJD consultaProduto;
    ModeloTabela modelo;
    
    ControllerVenda controleVenda = new ControllerVenda();
    Font font = new Font("Yu Gothic UI Semibold",Font.PLAIN,12);
    /**
     * Creates new form VendaViewJD
     */
    public VendaViewJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Connection con = ConnectionFactory.getConnection();
        abrirVenda();
        lbCabecalho6.setText("Venda n° : "+codVenda);
        txtValorTotal.setText("0");
        txtDesconto.setText("0");
        tabelaPesquisa.getTableHeader().setFont(font);
        tabelaItensVenda.getTableHeader().setFont(font);
        //tabelaPesquisa.getTableHeader().setForeground(new Color(0,50,199));
        //btnBuscar.setBackground(new Color(0,0,0,0));

        // Pega data do sistema
        SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
        Date atual = new Date();
        jftData.setText(data.format(atual));
        txtValorTotal.setText("0");
        txtDesconto.setText("0");
        txtDinheiro.setText("0");
        txtCartao.setText("0");
        tabelaPesquisa.getTableHeader().setFont(font);
        tabelaItensVenda.getTableHeader().setFont(font);
    }

      VendaViewJD(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Connection con = ConnectionFactory.getConnection();
        abrirVenda();
        lbCabecalho6.setText("Venda n° : "+codVenda);
        txtValorTotal.setText("0");
        txtDesconto.setText("0");
        txtDinheiro.setText("0");
        txtCartao.setText("0");
        //btnBuscar.setBackground(new Color(0,0,0,0));

        // Pega data do sistema
        SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
        Date atual = new Date();
        jftData.setText(data.format(atual));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jpCabecalho6 = new javax.swing.JPanel();
        lbCabecalho6 = new javax.swing.JLabel();
        lbVendaLogo6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtProdutoNome = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        txtValorUnitario = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtDesconto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPesquisa = new javax.swing.JTable();
        txtNomeProduto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jftData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaItensVenda = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        txtCartao = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu de Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novas/897226_balance spendings_budget_money_save money_icon.png"))); // NOI18N
        jButton1.setText("Finalizar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novas/728918_cancel_error_exit_fault_alert_icon.png"))); // NOI18N
        jButton2.setText("Cancelar venda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 490, 70));

        jpCabecalho6.setBackground(new java.awt.Color(0, 88, 227));
        jpCabecalho6.setForeground(new java.awt.Color(255, 255, 255));
        jpCabecalho6.setMaximumSize(new java.awt.Dimension(853, 29));
        jpCabecalho6.setMinimumSize(new java.awt.Dimension(853, 29));

        lbCabecalho6.setBackground(new java.awt.Color(0, 88, 227));
        lbCabecalho6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lbCabecalho6.setForeground(new java.awt.Color(255, 255, 255));
        lbCabecalho6.setText("Venda nº 999");
        lbCabecalho6.setMaximumSize(new java.awt.Dimension(853, 29));
        lbCabecalho6.setMinimumSize(new java.awt.Dimension(853, 29));
        lbCabecalho6.setPreferredSize(new java.awt.Dimension(853, 29));

        lbVendaLogo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/venda.png"))); // NOI18N

        javax.swing.GroupLayout jpCabecalho6Layout = new javax.swing.GroupLayout(jpCabecalho6);
        jpCabecalho6.setLayout(jpCabecalho6Layout);
        jpCabecalho6Layout.setHorizontalGroup(
            jpCabecalho6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCabecalho6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVendaLogo6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCabecalho6, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jpCabecalho6Layout.setVerticalGroup(
            jpCabecalho6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCabecalho6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(lbVendaLogo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jpCabecalho6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -1, 1070, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Preço :");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Estoque : ");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nome : ");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Codigo : ");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        txtProdutoNome.setEditable(false);
        txtProdutoNome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        txtEstoque.setEditable(false);
        txtEstoque.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        txtValorUnitario.setEditable(false);
        txtValorUnitario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnAdd.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(204, 0, 0));
        btnDeletar.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("Deletar");
        btnDeletar.setBorder(null);
        btnDeletar.setBorderPainted(false);
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setFocusPainted(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Qtd_Venda :");

        txtQuantidade.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusGained(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyReleased(evt);
            }
        });

        txtDesconto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescontoFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Desconto :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtValorUnitario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDesconto)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 540, 290));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 12))); // NOI18N

        tabelaPesquisa = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tabelaPesquisa.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        tabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Valor_Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPesquisa.getTableHeader().setReorderingAllowed(false);
        tabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPesquisa);

        txtNomeProduto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtNomeProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeProdutoMouseClicked(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultar_produto.png"))); // NOI18N
        btnBuscar.setText("Pesquisar");
        btnBuscar.setToolTipText("Pesquisar Produtos");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jftData.setForeground(new java.awt.Color(0, 0, 0));
        try {
            jftData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftData.setEnabled(false);
        jftData.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Data : ");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Produto : ");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("CPF  :");

        txtNomeCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Nome :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(txtNomeProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jftData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 540, 290));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Carrinho de Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        tabelaItensVenda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        tabelaItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelaItensVenda);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 490, 290));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Detalhes da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 12))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("VALOR TOTAL DA VENDA :");

        txtValorTotal.setEditable(false);
        txtValorTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        txtValorTotal.setForeground(new java.awt.Color(204, 0, 0));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Dinheiro :");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Cartão :");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel14.setText("Troco :");

        txtDinheiro.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        txtCartao.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        txtTroco.setEditable(false);
        txtTroco.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(65, 65, 65)
                                .addComponent(txtTroco))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 490, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1116, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyReleased
        String sql = "SELECT nome from clientes where cpf like ?";
        
        try {
            Connection con = ConnectionFactory.getConnection();
            PreparedStatement st = null;
            ResultSet rs = null;
            st = con.prepareStatement(sql);
            st.setString(1, txtCpf.getText());
            rs = st.executeQuery();
            
            while(rs.next()) {
                txtNomeCliente.setText(rs.getString("nome"));
            }
            
            
        } catch (Exception e) {
            
        }
        
        if (evt.getKeyCode() == evt.VK_BACK_SPACE){
            txtNomeCliente.setText(null);
        }
    }//GEN-LAST:event_txtCpfKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
       pesquisarProdutos();
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisaMouseClicked
         
        try {
            preencherProduto();
            somaProdutos();
        } catch (Exception e) {
        }

        
        
    }//GEN-LAST:event_tabelaPesquisaMouseClicked

    private void txtQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusGained
       
        
        
    }//GEN-LAST:event_txtQuantidadeFocusGained

    private void txtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyReleased
        try {
            somaProdutos();
        } catch (SQLException ex) {
            Logger.getLogger(VendaViewJD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtQuantidadeKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
   
    
        int idVenda,quantidade = 0 ;
        Connection con = ConnectionFactory.getConnection();
        ResultSet rs = null;
        Statement stm;
        
        try {
            stm = con.createStatement(rs.TYPE_SCROLL_INSENSITIVE,rs.CONCUR_READ_ONLY);
            rs = stm.executeQuery("select * from produtos where nome = '"+txtProdutoNome.getText()+"'");
            rs.first();
            quantidade = rs.getInt("quantidade");
            if(quantidade >= Integer.parseInt(txtQuantidade.getText())){
                 
                 modelovenda.setNomeProduto(txtProdutoNome.getText());
                 modelovenda.setQtdItens(Integer.parseInt(txtQuantidade.getText()));
                 modelovenda.setId(codVenda);
                 try {
            controleVenda.adicionar(modelovenda);
        } catch (SQLException ex) {
            Logger.getLogger(VendaViewJD.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
                 
                 
                 try {

            preencherItensVenda("select * from produtos inner join tbitemvenda on produtos.codigo = tbitemvenda.idProduto inner join tbvendas on tbvendas.id = tbitemvenda.idVenda where tbvendas.id = "+codVenda);
        } catch (Exception ex) {
            Logger.getLogger(VendaViewJD.class.getName()).log(Level.SEVERE, null, ex);
        }
                
            }else{
                JOptionPane.showMessageDialog(null, "Quantidade informada não está disponivel no estoque");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VendaViewJD.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        try{ 

       // Statement stm = con.createStatement(rs.TYPE_SCROLL_INSENSITIVE,rs.CONCUR_READ_ONLY);
        //rs = stm.executeQuery("SELECT * FROM produtos where nome =' "+txtNomeProduto.getText()+"'");
        //rs.first();
        
        }catch(Exception e){
            
        }
        
        try {
            somaProdutos();
        } catch (SQLException ex) {
            Logger.getLogger(VendaViewJD.class.getName()).log(Level.SEVERE, null, ex);
        }

        pesquisarProdutos();
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
       /* String nome = txtNomeCliente.getText();
        String cpf = txtCpf.getText();
        Clientes clientes = new Clientes();
        ClientesDAO clientesDAO = new ClientesDAO();
       // clientes = (Clientes) clientesDAO.buscarClientesPeloNome(nome);
        //clientes = (Clientes) clientesDAO.buscarClientesPeloCpf(cpf);

        FormPagamentos formPagamentos = new FormPagamentos(this, rootPaneCheckingEnabled);
        formPagamentos.txtTotal.setText(txtValorTotal.getText());
        formPagamentos.cliente = clientes;
        formPagamentos.modelo = modelo;
        formPagamentos.setVisible(true);
        this.dispose();
        */    
            
       

       
        if(txtNomeCliente.getText().isEmpty() || txtCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe os dados do cliente.");
        }else {
            
            Double dinheiro , cartao ,total_pago , total_venda , troco;
            dinheiro = Double.valueOf(txtDinheiro.getText());
            cartao = Double.valueOf(txtCartao.getText());
            total_venda = Double.valueOf(txtValorTotal.getText());
            total_pago = dinheiro + cartao;
            troco = total_pago - total_venda;
            txtTroco.setText(String.valueOf(troco));
            
            modelovenda.setId(codVenda);
            modelovenda.setNomeCliente(txtNomeCliente.getText());
            modelovenda.setData(jftData.getText());
            modelovenda.setCpfCliente(txtCpf.getText());
            modelovenda.setSubTotal(Float.parseFloat(txtValorTotal.getText()));
            controleVenda.finalizarVenda(modelovenda);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            controleVenda.cancelarVenda();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VendaViewJD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNomeProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeProdutoMouseClicked

       //NÂO USADO NO MOMENTO 
      /*  ProdutosConsultaJD pd = new ProdutosConsultaJD(this, rootPaneCheckingEnabled);
       * pd.setVisible(true);
       */
    }//GEN-LAST:event_txtNomeProdutoMouseClicked

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        
        if (tabelaItensVenda.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela Itens da venda para remover .");
        }else {
        try {
            int idvenda ;
            Connection con = ConnectionFactory.getConnection();
            ResultSet rs = null ;
            Statement stm = con.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_READ_ONLY);
            rs = stm.executeQuery("select * from produtos inner join tbitemvenda on produtos.codigo = tbitemvenda.idProduto inner join tbvendas on tbvendas.id = tbitemvenda.idVenda where tbvendas.id = "+codVenda);
            rs.last();
            idvenda = rs.getInt("idVenda");
            JOptionPane.showMessageDialog(null,"id encontrado");
            

            controleVenda.attProduto();
            
           
           
           

            String sqll = "delete from tbitemvenda where idVenda = ? ";
            PreparedStatement st = con.prepareStatement(sqll);
            st.setInt(1, idvenda);
            st.execute();
            st.close();
            JOptionPane.showMessageDialog(null,"excluido");
            
            
            
           
            
            
        }catch(Exception e ){
                JOptionPane.showMessageDialog(null,"ERRO : " + e);
            }
      
            pesquisarProdutos();
            ArrayList dados = new ArrayList();
      
            String[] Colunas = new String[]{"Descrição","Quantidade","Valor total"};
            
            
            ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            JTable table = new JTable(modelo);
            tabelaItensVenda.setModel(modelo);
            tabelaItensVenda.getColumnModel().getColumn(0).setPreferredWidth(400);
            tabelaItensVenda.getColumnModel().getColumn(0).setResizable(false);
            tabelaItensVenda.getColumnModel().getColumn(1).setPreferredWidth(160);
            tabelaItensVenda.getColumnModel().getColumn(1).setResizable(false);
            tabelaItensVenda.getColumnModel().getColumn(2).setPreferredWidth(308);
            tabelaItensVenda.getColumnModel().getColumn(2).setResizable(false);

            tabelaItensVenda.getTableHeader().setReorderingAllowed(false);
            tabelaItensVenda.setAutoResizeMode(tabelaItensVenda.AUTO_RESIZE_OFF);
            tabelaItensVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
            modelo.removeRow((int)tabelaItensVenda.getValueAt(tabelaItensVenda.getSelectedRow(), 1));
            
            try {
                preencherItensVenda("select * from produtos inner join tbitemvenda on produtos.codigo = tbitemvenda.idProduto inner join tbvendas on tbvendas.id = tbitemvenda.idVenda where tbvendas.id = "+codVenda);
            } catch (Exception e) {
            }
           
           
           
            
            
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        // NAO USADO NO MOMENTO // METODO PARA PEGAR OS DADOS DA TELA DE CONSULTA
        /*  
       Produtos produto = new Produtos();
        
        try{
            //coloca dados do produto a partir do produto selecionado 
            //na tela de consulta de produto da venda
            produto.setCodigo(consultaProduto.getProduto().getCodigo());
            produto.setNome_P(consultaProduto.getProduto().getNome_P());
            produto.setQuantidade(consultaProduto.getProduto().getQuantidade());
            produto.setTipo(consultaProduto.getProduto().getTipo());
            produto.setValor_v(consultaProduto.getProduto().getValor_v());

            //coloca na tela de venda nome e valor do produto
            txtNomeProduto.setText(produto.getNome_P());
            txtValorUnitario.setText(produto.getValor_v().toString());
            txtQuantidade.setText("1");
            //verifica se o produto selecionado tem mais que 1 item no estoque
            
            
        }
        catch(Exception e){
            
        }
        
        
        */
        
        
    }//GEN-LAST:event_formWindowActivated

    private void txtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusLost
        try {
            somaProdutos();
        } catch (SQLException ex) {
            Logger.getLogger(VendaViewJD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtDescontoFocusLost

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaViewJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaViewJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaViewJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaViewJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaViewJD dialog = new VendaViewJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
           }
// METODOS 
   private void desconto(){
       txtValorTotal.setText(String.valueOf(Double.parseDouble(txtValorTotal.getText()) - Double.parseDouble(txtDesconto.getText())));
       
       
   }     
   public void pesquisarProdutos(){
       String sql = "SELECT codigo as Codigo, nome as Nome ,quantidade as Quantidade , valor_v as Valor_Unitario from produtos where nome like ? ";
       
       try {
           Connection con = ConnectionFactory.getConnection();
           PreparedStatement st = con.prepareStatement(sql);
           ResultSet rs = null;
           st.setString(1, txtNomeProduto.getText()+ "%");
           rs = st.executeQuery();
           
         
               tabelaPesquisa.setModel(DbUtils.resultSetToTableModel(rs));
          
           
       } catch (Exception e) {
       }
   
   }
   public void abrirVenda(){
       try {
            Connection con = ConnectionFactory.getConnection();
            PreparedStatement st = con.prepareStatement("insert into tbvendas (subtotal) values (?) ");
            st.setFloat(1, 0);
            st.execute(); 
            st.close();
            
            ResultSet rs = null ;
            Statement stm = con.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_READ_ONLY);
            rs = stm.executeQuery("select * from tbvendas");
            rs.last();
            codVenda = rs.getInt("id");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro : " +e);
        }
       
       
   }
   
   
   public void somaProdutos() throws SQLException{
      total = 0;
      int qtd = 0;
      float valor = 0;
    try{  Connection con = ConnectionFactory.getConnection();
      ResultSet rs = null;
      Statement stm = con.createStatement(rs.TYPE_SCROLL_INSENSITIVE,rs.CONCUR_READ_ONLY);
      rs = stm.executeQuery("select * from tbitemvenda inner join produtos on tbitemvenda.idProduto = produtos.codigo where idVenda ="+codVenda);
     // rs.first();
       while (rs.next()) {  
           qtd  =rs.getInt("qtd_produto");
           valor = rs.getFloat("valor_v");
           total =total + rs.getFloat("valor_v")*rs.getInt("qtd_produto");
       }
     
       txtValorTotal.setText(String.valueOf(total));
      
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, "Erro : " +e);
    }
    
    desconto();
   }
   
   public void preencherItensVenda(String SQL) throws SQLException{
      ArrayList dados = new ArrayList();
      
      String[] Colunas = new String[]{"Codigo","Descrição","Quantidade","Valor total"};
      Connection con = ConnectionFactory.getConnection();
      ResultSet rs = null;
      Statement stm = con.createStatement(rs.TYPE_SCROLL_INSENSITIVE,rs.CONCUR_READ_ONLY);
      rs = stm.executeQuery(SQL);
      rs.first();
       do {      
           float valorproduto = rs.getFloat("valor_v");
           int qtdvendida = rs.getInt("qtd_produto");
           dados.add(new Object[]{rs.getInt("codigo"),rs.getString("nome"),rs.getInt("qtd_produto"),valorproduto * qtdvendida});
       } while (rs.next());
      
       modelo = new ModeloTabela(dados, Colunas);
       JTable table = new JTable(modelo);
       tabelaItensVenda.setModel(modelo);
       tabelaItensVenda.getColumnModel().getColumn(0).setPreferredWidth(80);
       tabelaItensVenda.getColumnModel().getColumn(0).setResizable(false);
       tabelaItensVenda.getColumnModel().getColumn(1).setPreferredWidth(133);
       tabelaItensVenda.getColumnModel().getColumn(1).setResizable(false);
       tabelaItensVenda.getColumnModel().getColumn(2).setPreferredWidth(133);
       tabelaItensVenda.getColumnModel().getColumn(2).setResizable(false);
       tabelaItensVenda.getColumnModel().getColumn(3).setPreferredWidth(120);
       tabelaItensVenda.getColumnModel().getColumn(3).setResizable(false);
       
       tabelaItensVenda.getTableHeader().setReorderingAllowed(false);
       tabelaItensVenda.setAutoResizeMode(tabelaItensVenda.AUTO_RESIZE_OFF);
       tabelaItensVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       somaProdutos();
       
   }
   
   public void excluirItensVenda(String SQL) throws SQLException{
      ArrayList dados = new ArrayList();
      
      String[] Colunas = new String[]{"Descrição","Quantidade","Valor total"};
      Connection con = ConnectionFactory.getConnection();
      ResultSet rs = null;
      Statement stm = con.createStatement(rs.TYPE_SCROLL_INSENSITIVE,rs.CONCUR_READ_ONLY);
      rs = stm.executeQuery(SQL);
      rs.first();
       do {      
           float valorproduto = rs.getFloat("valor_v");
           int qtdvendida = rs.getInt("qtd_produto");
           dados.add(new Object[]{rs.getString("nome"),rs.getInt("qtd_produto"),valorproduto * qtdvendida});
       } while (rs.next());
      
       ModeloTabela modelo = new ModeloTabela(dados, Colunas);
       tabelaItensVenda.setModel(modelo);
       tabelaItensVenda.getColumnModel().getColumn(0).setPreferredWidth(400);
       tabelaItensVenda.getColumnModel().getColumn(0).setResizable(false);
       tabelaItensVenda.getColumnModel().getColumn(1).setPreferredWidth(160);
       tabelaItensVenda.getColumnModel().getColumn(1).setResizable(false);
       tabelaItensVenda.getColumnModel().getColumn(2).setPreferredWidth(308);
       tabelaItensVenda.getColumnModel().getColumn(2).setResizable(false);
       
       tabelaItensVenda.getTableHeader().setReorderingAllowed(false);
       tabelaItensVenda.setAutoResizeMode(tabelaItensVenda.AUTO_RESIZE_OFF);
       tabelaItensVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       somaProdutos();
      
       tabelaItensVenda.remove(tabelaItensVenda.getSelectedRow());
      
      
      
      
       
       
       
       
   }
   
        public void preencherProduto(){
            txtCodigo.setText(tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow(), 0).toString());
            txtProdutoNome.setText(tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow(), 1).toString());
            txtEstoque.setText(tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow(), 2).toString());
            txtQuantidade.setText("1");
            txtValorUnitario.setText(tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow(), 3).toString());
        }
        
        
    public int getCodVenda() {
        return codVenda;
    }

    public void setCodVenda(int codVenda) {
        this.codVenda = codVenda;
    }

    public float getPreco_produto() {
        return preco_produto;
    }

    public void setPreco_produto(float preco_produto) {
        this.preco_produto = preco_produto;
    }

    public float getTotal() {
        return total;
    }

    public void setTotal(float total) {
        this.total = total;
    }

    public JFormattedTextField getJftData() {
        return jftData;
    }

    public void setJftData(JFormattedTextField jftData) {
        this.jftData = jftData;
    }

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public void setTxtCodigo(JTextField txtCodigo) {
        this.txtCodigo = txtCodigo;
    }

    public JTextField getTxtDesconto() {
        return txtDesconto;
    }

    public void setTxtDesconto(JTextField txtDesconto) {
        this.txtDesconto = txtDesconto;
    }

    public JTextField getTxtEstoque() {
        return txtEstoque;
    }

    public void setTxtEstoque(JTextField txtEstoque) {
        this.txtEstoque = txtEstoque;
    }

    public JTextField getTxtProdutoNome() {
        return txtProdutoNome;
    }

    public void setTxtProdutoNome(JTextField txtProdutoNome) {
        this.txtProdutoNome = txtProdutoNome;
    }

    public JTextField getTxtQuantidade() {
        return txtQuantidade;
    }

// METODOS FIM
    public void setTxtQuantidade(JTextField txtQuantidade) {
        this.txtQuantidade = txtQuantidade;
    }

    public JFormattedTextField getTxtCpf() {
        return txtCpf;
    }

    public void setTxtCpf(JFormattedTextField txtCpf) {
        this.txtCpf = txtCpf;
    }

    public JTextField getTxtNomeCliente() {
        return txtNomeCliente;
    }

    public void setTxtNomeCliente(JTextField txtNomeCliente) {
        this.txtNomeCliente = txtNomeCliente;
    }

    public JTextField getTxtNomeProduto() {
        return txtNomeProduto;
    }

    public void setTxtNomeProduto(JTextField txtNomeProduto) {
        this.txtNomeProduto = txtNomeProduto;
    }

    public JTextField getTxtValorTotal() {
        return txtValorTotal;
    }

    public void setTxtValorTotal(JTextField txtValorTotal) {
        this.txtValorTotal = txtValorTotal;
    }

    public JTextField getTxtValorUnitario() {
        return txtValorUnitario;
    }

    public void setTxtValorUnitario(JTextField txtValorUnitario) {
        this.txtValorUnitario = txtValorUnitario;
    }
        
        
        
        
        
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JFormattedTextField jftData;
    private javax.swing.JPanel jpCabecalho6;
    private javax.swing.JLabel lbCabecalho6;
    private javax.swing.JLabel lbVendaLogo6;
    private javax.swing.JTable tabelaItensVenda;
    private javax.swing.JTable tabelaPesquisa;
    private javax.swing.JTextField txtCartao;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JFormattedTextField txtCpf;
    public javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtDinheiro;
    public javax.swing.JTextField txtEstoque;
    public javax.swing.JTextField txtNomeCliente;
    public javax.swing.JTextField txtNomeProduto;
    public javax.swing.JTextField txtProdutoNome;
    public javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTroco;
    public javax.swing.JTextField txtValorTotal;
    public javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables
}
